In [1]:
import torch
import gym
import numpy as np

from envs import EconModel, AiyagariEnv
from utils import configObj
from dpsolver import DPSolver

import matplotlib.pyplot as plt

In [2]:
config_name = 'config'
cfg = configObj(config_name,verbose=False)
env = AiyagariEnv(cfg)
dp = DPSolver(env)

In [3]:
v = dp.result.v.reshape(200, 2).T

# fig, ax = plt.subplots(figsize=(20, 15))
# plt.plot(env.a_vals, v[0, :], label='z=0.1')
# plt.plot(env.a_vals, v[1, :], label='z=1')
# plt.legend(fontsize=20);

a = dp.result.sigma.reshape(200, 2).T

# fig, ax = plt.subplots(figsize=(20, 15))
# plt.plot(env.a_vals, env.a_vals[a[0]])
# plt.plot(env.a_vals, env.a_vals[a[1]])
# plt.plot(env.a_vals, env.a_vals, 'k--')

In [16]:
state = env.gen_states(sampling=False, B=6)
state

tensor([[1.0000e-10, 0.0000e+00],
        [9.0000e+00, 0.0000e+00],
        [1.8000e+01, 0.0000e+00],
        [1.0000e-10, 1.0000e+00],
        [9.0000e+00, 1.0000e+00],
        [1.8000e+01, 1.0000e+00]])

In [17]:
action = state[:, 0:1].clone() / 2

In [18]:
reward, next_state = env.transit(state.clone(), action)

In [19]:
reward.shape

torch.Size([6, 1])

In [20]:
next_state.shape

torch.Size([6, 2])

In [21]:
state, next_state

(tensor([[1.0000e-10, 0.0000e+00],
         [9.0000e+00, 0.0000e+00],
         [1.8000e+01, 0.0000e+00],
         [1.0000e-10, 1.0000e+00],
         [9.0000e+00, 1.0000e+00],
         [1.8000e+01, 1.0000e+00]]),
 tensor([[5.0000e-11, 0.0000e+00],
         [4.5000e+00, 0.0000e+00],
         [9.0000e+00, 0.0000e+00],
         [5.0000e-11, 0.0000e+00],
         [4.5000e+00, 1.0000e+00],
         [9.0000e+00, 1.0000e+00]]))

In [22]:
reward

tensor([[-2.3026],
        [ 1.5454],
        [ 2.2279],
        [ 0.0000],
        [ 1.7210],
        [ 2.3204]])